### ISSUE TITLE
web-example is not working

### ISSUE THREAD

**Issue by smartpunter** [nebulasio/neb.js#19]
https://github.com/nebulasio/neb.js/blob/master/example/example.html
Seems like a mix up of nodejs code with html, please fix.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter ,
Sorry for the delay. We are currently looking into this issue, stay tuned.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter the example.html has been updated. Please have a check.
More explanation will be added to the example later :)

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter some note has also been added to this page, thanks!

**Comment by smartpunter** [comment]
Requesting test tokens on web example doesn't work, it requests this url.
https://testnet.nebulas.io/claim/api/claim/0.7042040317612817test@demo.io/n1cmNf7qMKMK3io61cYjtuLqsYWVCLf1DpR//v1

I really recommend you to assign 1-2 persons for checking the quality of documentation, just go through each page and repeat instructions and list errors and unperfectness.

For now it is really disappointing experience, to start developing for nebulas. Something must be done, before too many people got disappointed.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter , Apologies for our flaws. Nebulas has been developing so rapidly that some documents might not has been updated timely. We agree it is fairly important to update documents alone with developing new features, and you could found quite a lot of commits recently in our main wiki https://github.com/nebulasio/wiki/wiki . We promise to update other parts of documents in nebulas as well as soon as possible.

For this particular issue, initialize your keystore from https://github.com/nebulasio/web-wallet and claim nas in https://testnet.nebulas.io/claim/ could be the recommend way to start developing. 
Maybe the web-wallet (https://github.com/nebulasio/web-wallet ) is a better example than this.

**Comment by ChengOrangeJu** [comment]
Since there are a lot of developers starting developing on Nebulas, claiming tokens in our testnet might take some time. You could check the balance of your account after some time to ensure the transfer is done
