### ISSUE TITLE
Broken link to online documentation

### ISSUE THREAD

**Issue by smartpunter** [nebulasio/neb.js#26]
https://nebulasio.github.io/neb.js/index.html

Link 'Public API documentation link' leads to the same page.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter, thanks for your advice, as for neb.js, generated documents can be found in /documents folder. The recursive link is removed, thanks again

**Comment by smartpunter** [comment]
I still believe, that i should be able to vie documentation online, before downloading and compiling the file.
