### ISSUE TITLE
Util to convert unit (e.g. Wei to NAS)

### ISSUE THREAD

**Issue by woniesong92** [nebulasio/neb.js#35]
Would you guys be interested in adding a utils function that converts currency units?

Something like [toWei](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3towei) from web3.

**Comment by yupnano** [comment]
neb.js has currency units conversion,  please read this file [`neb.js/lib/utils/unit.js`](https://github.com/nebulasio/neb.js/blob/master/lib/utils/unit.js)
