### ISSUE TITLE
Compatibility with React Native?

### ISSUE THREAD

**Issue by ericluwj** [nebulasio/neb.js#37]
We realized this library was not compatible with React Native, so we modified this library to create an example that works on React Native:
[https://github.com/weoneco/react-native-nebjs-example](https://github.com/weoneco/react-native-nebjs-example)

**Comment by yupnano** [comment]
The reason for this incompatible issue might be that React doesn't support ES6.

**Comment by ericluwj** [comment]
Not exactly, there was at least one issue: one of the utils file uses `crypto` module which is only present in Node.js and hence raises an error when compiled with React Native.

**Comment by yupnano** [comment]
With the feedback of community developers, the latest code is now compatible with React now.
Please try the latest code again.

**Comment by ericluwj** [comment]
![img_0097](https://user-images.githubusercontent.com/1736023/40528974-612ca6d4-6025-11e8-8c0e-5b009a7426da.PNG)
The missing `crypto` module error still exists using the latest `master` branch.

**Comment by yupnano** [comment]
Sorry that I remembered wrong. It is Nebpay that now compatible with React.
neb.js still has some ES6 syntax, we will go through the code and change to ES5 later. Then we will replay you here.

**Comment by catalsdevelop** [comment]
it's not about `crypto` or react, you need transpile your es6/7/8 code to es5 with babel or other compilers unless your client or browser fully support es6. I've made a cordova light wallet which source code is es6 use neb.js , and it worked fine.

**Comment by yupnano** [comment]
As @catalsdevelop said, please transpile es6/7/8 code to es5 with babel.
