### ISSUE TITLE
any api to get block info from a transaction hash?

### ISSUE THREAD

**Issue by catalsdevelop** [nebulasio/neb.js#40]
I know we can retrieve transactions data from block height or number , but if a transaction hash supplied, how can I get the related block info?

**Comment by ChengOrangeJu** [comment]
from explorer https://explorer.nebulas.io/#/

**Comment by catalsdevelop** [comment]
thx for your reply, I think we need enhance nebulas' rpc api `GetTransactionReceipt `, which could contains simple block height/hash information.
