### ISSUE TITLE
numeric overflow

### ISSUE THREAD

**Issue by act262** [nebulasio/neb.js#43]
code like:
`
var tx = new nebulas.Transaction(1, sAccount, toAddress, "9999999999999999999999", nonce, 1000000, 2000000);
tx.signTransaction();
neb.api.sendRawTransaction({data:tx.toProtoString()})
`
value 这里数值溢出,交易发送成功, 在 explorer 中可以看到一直处于 pending 状态, 一段时间后才展示 fail

**Comment by yupnano** [comment]
发送交易前，最好先用neb.api.call 模拟执行一下，以排除错误。
错误的交易也可以成功发送，但不会成功上链，最终执行结果是fail。
