### ISSUE TITLE
mock javascript contract can't return function result

### ISSUE THREAD

**Issue by Chuangludeng** [nebulasio/neb.js#46]
使用合约模拟功能,调用合约函数,不能显示函数返回值
显示 undefined

看了一下好像是nvm没有返回函数的返回值?

![default](https://user-images.githubusercontent.com/16982114/40927262-e08867d2-6850-11e8-844d-70cc2c1d73d8.png)

**Comment by yuxizhe** [comment]
fixed in https://github.com/nebulasio/neb.js/pull/47

**Comment by cctanfujun** [comment]
请问一下如何使用这个mock的功能  有相关文档可以学习一下吗

**Comment by xiwangzishi** [comment]
@cctanfujun 

可以使用星云合约本地开发调试工器 `nebulas cat`

快来 https://tool.forfunapp.com 下载体验吧。
