### ISSUE TITLE
Difference between neb.js and nebulas.js

### ISSUE THREAD

**Issue by 1c7** [nebulasio/neb.js#61]
## README say: 
![image](https://user-images.githubusercontent.com/1804755/44326499-76c91100-a48e-11e8-9911-d20f0b6ed4dc.png)
I still don't know when to use which.

## File size have huge difference
![image](https://user-images.githubusercontent.com/1804755/44326547-93654900-a48e-11e8-9e2f-7c11f9833197.png)

## Question
What the difference between these 2 file `neb.js` and `nebulas.js`?     
What can I do with these 2?

**Comment by 1c7** [comment]
## Why I have to `gulp` it?
Why can't I just `npm install nebjs` 
(I am not node.js developer, not sure how npm module work exactly)

**Comment by nebulashub** [comment]
`neb.js` only contains the rpc interface for nebulas.
`nebulas.js` contains the all feature for address generate, transaction sign and rpc broadcast.

**Comment by qywang2012** [comment]
neb.js only contains the rpc interface for nebulas.
nebulas.js contains the all feature for address generate, transaction sign and rpc broadcast.

**Comment by 1c7** [comment]
@nebulashub Thanks! 
would you mind update readme with this new description?

**Comment by 1c7** [comment]
@qywang2012 Thank you!

**Comment by 1c7** [comment]
close issue, thanks again
