### ISSUE TITLE
General Question: How to build Nebulas SDK for different language?

### ISSUE THREAD

**Issue by 1c7** [nebulasio/neb.js#62]
This is a general question, not about neb.js alone. I just want post it here :)

## Question: How to build Nebulas SDK for different language?

Base on my understanding:     

1. Implement [RPC](https://github.com/nebulasio/wiki/blob/master/rpc.md)
* GetNebState
* GetAccountState
* LatestIrreversibleBlock
* Call
* SendRawTransaction
* GetBlockByHash
* GetBlockByHeight
* GetTransactionReceipt
* GetTransactionByContract
* GetGasPrice
* EstimateGas
* GetEventsByHash
* Subscribe
* GetDynasty

2. Implement [RPC-admin](https://github.com/nebulasio/wiki/blob/master/rpc_admin.md)
* NodeInfo
* Accounts
* NewAccount
* UnLockAccount
* LockAccount
* SignTransactionWithPassphrase
* SendTransactionWithPassphrase
* SendTransaction
* SignHash
* StartPprof
* GetConfig

## Essentially what SDK does is
Send HTTP request to **certain address** with **correct format**

### Question: Are my assumption correct? 
These 2 step are all it take to build a Nebulas SDK? just implement `rpc` and `rpc-admin` base on document link above, is there anything else?  

I am not trying to build a Nebulas SDK right now, I am just curious **How** to build one

Thanks

**Comment by yupnano** [comment]
Hi，besides http request, the sdk should also implements `account` and `transaction` related functions, such as create new account/ create address/ hash transaction/ sign transaction.

![image](https://user-images.githubusercontent.com/5012612/44970268-65e6c800-af83-11e8-8e5d-e711734824c3.png)

**Comment by 1c7** [comment]
@yupnano  got it, Thanks for reply!

## So, Conclusion is:
a proper Nebulas SDK have 2 part:     

1. HTTP request part (this one is easy, just make sure the format is right, like `GetNebState` is just a GET request with no parameter)    

2. Create account, Sign transaction, etc..  [implement them as RPC-admin defined](https://github.com/nebulasio/wiki/blob/master/rpc_admin.md) (this one is hard, because have to deal with Cryptography in each programming language)

Am I understanding this correctly?
is so, I am gonna close this issue.

Thanks again for reply!

**Comment by yupnano** [comment]
Yes, you are right.
Please refer the SDK of other languages:
 - PHP: https://github.com/nebulasio/neb.php
- Java: https://github.com/nebulasio/neb.java
- Python: https://github.com/nebulasio/neb.py
- Ruby: https://github.com/NaixSpirit/neb.rb
- Go: https://github.com/vigozhang/neb-go

**Comment by 1c7** [comment]
@yupnano Thank you!
